<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Joli\Jane\Tests\Expected\Schema1\Model;

class Test
{
    /**
     * @var \Joli\Jane\Tests\Expected\Schema2\Model\Foo
     */
    protected $foo;

    /**
     * @return \Joli\Jane\Tests\Expected\Schema2\Model\Foo
     */
    public function getFoo(): ?\Joli\Jane\Tests\Expected\Schema2\Model\Foo
    {
        return $this->foo;
    }

    /**
     * @param \Joli\Jane\Tests\Expected\Schema2\Model\Foo $foo
     *
     * @return self
     */
    public function setFoo(?\Joli\Jane\Tests\Expected\Schema2\Model\Foo $foo): self
    {
        $this->foo = $foo;

        return $this;
    }
}
