<?php

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Joli\Jane\Tests\Expected\Model;

class BazBaz
{
    /**
     * @var string
     */
    protected $baz;

    /**
     * @return string
     */
    public function getBaz()
    {
        return $this->baz;
    }

    /**
     * @param string $baz
     *
     * @return self
     */
    public function setBaz($baz = null)
    {
        $this->baz = $baz;

        return $this;
    }
}
